// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: HBTbJNVG66
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Text from "../../Text"; // plasmic-import: sIxKMhfpOf/component
import Button from "../../Button"; // plasmic-import: IDy-UAQYMv/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicSummaryTotalUnclaimed.module.css"; // plasmic-import: HBTbJNVG66/css

export type PlasmicSummaryTotalUnclaimed__VariantMembers = {};

export type PlasmicSummaryTotalUnclaimed__VariantsArgs = {};
type VariantPropType = keyof PlasmicSummaryTotalUnclaimed__VariantsArgs;
export const PlasmicSummaryTotalUnclaimed__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSummaryTotalUnclaimed__ArgsType = {};
type ArgPropType = keyof PlasmicSummaryTotalUnclaimed__ArgsType;
export const PlasmicSummaryTotalUnclaimed__ArgProps = new Array<ArgPropType>();

export type PlasmicSummaryTotalUnclaimed__OverridesType = {
  root?: p.Flex<"div">;
  button?: p.Flex<typeof Button>;
};

export interface DefaultSummaryTotalUnclaimedProps {
  className?: string;
}

export const defaultSummaryTotalUnclaimed__Args: Partial<PlasmicSummaryTotalUnclaimed__ArgsType> =
  {};

function PlasmicSummaryTotalUnclaimed__RenderFunc(props: {
  variants: PlasmicSummaryTotalUnclaimed__VariantsArgs;
  args: PlasmicSummaryTotalUnclaimed__ArgsType;
  overrides: PlasmicSummaryTotalUnclaimed__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign(
    {},
    defaultSummaryTotalUnclaimed__Args,
    props.args
  );
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__bBXp4)}>
        <div className={classNames(projectcss.all, sty.freeBox__gs04)}>
          <Text
            className={classNames("__wab_instance", sty.text__bwkas)}
            colors={"gray" as const}
            weight={"medium" as const}
          />

          <Text
            className={classNames("__wab_instance", sty.text__sbdlJ)}
            colors={"red" as const}
            weight={"medium" as const}
          />
        </div>

        <Button
          data-plasmic-name={"button"}
          data-plasmic-override={overrides.button}
          className={classNames("__wab_instance", sty.button)}
          size={"md" as const}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "button"],
  button: ["button"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  button: typeof Button;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSummaryTotalUnclaimed__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSummaryTotalUnclaimed__VariantsArgs;
    args?: PlasmicSummaryTotalUnclaimed__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSummaryTotalUnclaimed__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSummaryTotalUnclaimed__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicSummaryTotalUnclaimed__ArgProps,
      internalVariantPropNames: PlasmicSummaryTotalUnclaimed__VariantProps
    });

    return PlasmicSummaryTotalUnclaimed__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicSummaryTotalUnclaimed";
  } else {
    func.displayName = `PlasmicSummaryTotalUnclaimed.${nodeName}`;
  }
  return func;
}

export const PlasmicSummaryTotalUnclaimed = Object.assign(
  // Top-level PlasmicSummaryTotalUnclaimed renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    button: makeNodeComponent("button"),

    // Metadata about props expected for PlasmicSummaryTotalUnclaimed
    internalVariantProps: PlasmicSummaryTotalUnclaimed__VariantProps,
    internalArgProps: PlasmicSummaryTotalUnclaimed__ArgProps
  }
);

export default PlasmicSummaryTotalUnclaimed;
/* prettier-ignore-end */
