// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: OWF7fqE1kH
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicRootContainer.module.css"; // plasmic-import: OWF7fqE1kH/css

export type PlasmicRootContainer__VariantMembers = {
  mb: "_110";
};

export type PlasmicRootContainer__VariantsArgs = {
  mb?: SingleChoiceArg<"_110">;
};

type VariantPropType = keyof PlasmicRootContainer__VariantsArgs;
export const PlasmicRootContainer__VariantProps = new Array<VariantPropType>(
  "mb"
);

export type PlasmicRootContainer__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicRootContainer__ArgsType;
export const PlasmicRootContainer__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicRootContainer__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultRootContainerProps {
  children?: React.ReactNode;
  mb?: SingleChoiceArg<"_110">;
  className?: string;
}

export const defaultRootContainer__Args: Partial<PlasmicRootContainer__ArgsType> =
  {};

function PlasmicRootContainer__RenderFunc(props: {
  variants: PlasmicRootContainer__VariantsArgs;
  args: PlasmicRootContainer__ArgsType;
  overrides: PlasmicRootContainer__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultRootContainer__Args, props.args);
  const $props = args;
  const $ctx = ph.useDataEnv?.() || {};

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox, {
          [sty.freeBoxmb__110]: hasVariant(variants, "mb", "_110")
        })}
      >
        {p.renderPlasmicSlot({
          defaultContents: null,
          value: args.children
        })}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicRootContainer__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicRootContainer__VariantsArgs;
    args?: PlasmicRootContainer__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicRootContainer__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicRootContainer__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicRootContainer__ArgProps,
      internalVariantPropNames: PlasmicRootContainer__VariantProps
    });

    return PlasmicRootContainer__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicRootContainer";
  } else {
    func.displayName = `PlasmicRootContainer.${nodeName}`;
  }
  return func;
}

export const PlasmicRootContainer = Object.assign(
  // Top-level PlasmicRootContainer renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicRootContainer
    internalVariantProps: PlasmicRootContainer__VariantProps,
    internalArgProps: PlasmicRootContainer__ArgProps
  }
);

export default PlasmicRootContainer;
/* prettier-ignore-end */
