// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: 5SbWwwlAWA
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Text from "../../Text"; // plasmic-import: sIxKMhfpOf/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicHeaderOverview.module.css"; // plasmic-import: 5SbWwwlAWA/css

export type PlasmicHeaderOverview__VariantMembers = {};

export type PlasmicHeaderOverview__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeaderOverview__VariantsArgs;
export const PlasmicHeaderOverview__VariantProps = new Array<VariantPropType>();

export type PlasmicHeaderOverview__ArgsType = {
  children?: React.ReactNode;
};

type ArgPropType = keyof PlasmicHeaderOverview__ArgsType;
export const PlasmicHeaderOverview__ArgProps = new Array<ArgPropType>(
  "children"
);

export type PlasmicHeaderOverview__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
};

export interface DefaultHeaderOverviewProps {
  children?: React.ReactNode;
  className?: string;
}

export const defaultHeaderOverview__Args: Partial<PlasmicHeaderOverview__ArgsType> =
  {};

function PlasmicHeaderOverview__RenderFunc(props: {
  variants: PlasmicHeaderOverview__VariantsArgs;
  args: PlasmicHeaderOverview__ArgsType;
  overrides: PlasmicHeaderOverview__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultHeaderOverview__Args, props.args);
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div
        data-plasmic-name={"freeBox"}
        data-plasmic-override={overrides.freeBox}
        className={classNames(projectcss.all, sty.freeBox)}
      >
        {p.renderPlasmicSlot({
          defaultContents: (
            <Text className={classNames("__wab_instance", sty.text__cJFzq)} />
          ),

          value: args.children
        })}

        <Text className={classNames("__wab_instance", sty.text__dfdvM)} />
      </div>

      <Text className={classNames("__wab_instance", sty.text__nqbXl)} />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeaderOverview__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeaderOverview__VariantsArgs;
    args?: PlasmicHeaderOverview__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeaderOverview__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeaderOverview__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeaderOverview__ArgProps,
      internalVariantPropNames: PlasmicHeaderOverview__VariantProps
    });

    return PlasmicHeaderOverview__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeaderOverview";
  } else {
    func.displayName = `PlasmicHeaderOverview.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderOverview = Object.assign(
  // Top-level PlasmicHeaderOverview renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicHeaderOverview
    internalVariantProps: PlasmicHeaderOverview__VariantProps,
    internalArgProps: PlasmicHeaderOverview__ArgProps
  }
);

export default PlasmicHeaderOverview;
/* prettier-ignore-end */
