// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: OiFeVBevre
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicProgress.module.css"; // plasmic-import: OiFeVBevre/css

export type PlasmicProgress__VariantMembers = {};

export type PlasmicProgress__VariantsArgs = {};
type VariantPropType = keyof PlasmicProgress__VariantsArgs;
export const PlasmicProgress__VariantProps = new Array<VariantPropType>();

export type PlasmicProgress__ArgsType = {};
type ArgPropType = keyof PlasmicProgress__ArgsType;
export const PlasmicProgress__ArgProps = new Array<ArgPropType>();

export type PlasmicProgress__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultProgressProps {
  className?: string;
}

export const defaultProgress__Args: Partial<PlasmicProgress__ArgsType> = {};

function PlasmicProgress__RenderFunc(props: {
  variants: PlasmicProgress__VariantsArgs;
  args: PlasmicProgress__ArgsType;
  overrides: PlasmicProgress__OverridesType;

  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;
  const args = Object.assign({}, defaultProgress__Args, props.args);
  const $props = args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__mrJs1)}>
        <div className={classNames(projectcss.all, sty.freeBox__ieLeV)} />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicProgress__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicProgress__VariantsArgs;
    args?: PlasmicProgress__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicProgress__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicProgress__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicProgress__ArgProps,
      internalVariantPropNames: PlasmicProgress__VariantProps
    });

    return PlasmicProgress__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicProgress";
  } else {
    func.displayName = `PlasmicProgress.${nodeName}`;
  }
  return func;
}

export const PlasmicProgress = Object.assign(
  // Top-level PlasmicProgress renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicProgress
    internalVariantProps: PlasmicProgress__VariantProps,
    internalArgProps: PlasmicProgress__ArgProps
  }
);

export default PlasmicProgress;
/* prettier-ignore-end */
