// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: ILn7OfVdq5H
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Icon from "../../Icon"; // plasmic-import: E1FwFPFP4L/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicTextNew.module.css"; // plasmic-import: ILn7OfVdq5H/css

export type PlasmicTextNew__VariantMembers = {
  weight: "medium" | "semiBold";
  size: "_10" | "_11" | "_12" | "_14" | "_16" | "_24" | "_28";
  withIconLeft: "withIconLeft";
  title: "title";
  colors: "gray" | "red" | "white";
};

export type PlasmicTextNew__VariantsArgs = {
  weight?: SingleChoiceArg<"medium" | "semiBold">;
  size?: SingleChoiceArg<"_10" | "_11" | "_12" | "_14" | "_16" | "_24" | "_28">;
  withIconLeft?: SingleBooleanChoiceArg<"withIconLeft">;
  title?: SingleBooleanChoiceArg<"title">;
  colors?: SingleChoiceArg<"gray" | "red" | "white">;
};

type VariantPropType = keyof PlasmicTextNew__VariantsArgs;
export const PlasmicTextNew__VariantProps = new Array<VariantPropType>(
  "weight",
  "size",
  "withIconLeft",
  "title",
  "colors"
);

export type PlasmicTextNew__ArgsType = {};
type ArgPropType = keyof PlasmicTextNew__ArgsType;
export const PlasmicTextNew__ArgProps = new Array<ArgPropType>();

export type PlasmicTextNew__OverridesType = {
  root?: p.Flex<"div">;
  freeBox?: p.Flex<"div">;
  h1?: p.Flex<"h1">;
};

export interface DefaultTextNewProps {
  weight?: SingleChoiceArg<"medium" | "semiBold">;
  size?: SingleChoiceArg<"_10" | "_11" | "_12" | "_14" | "_16" | "_24" | "_28">;
  withIconLeft?: SingleBooleanChoiceArg<"withIconLeft">;
  title?: SingleBooleanChoiceArg<"title">;
  colors?: SingleChoiceArg<"gray" | "red" | "white">;
  className?: string;
}

function PlasmicTextNew__RenderFunc(props: {
  variants: PlasmicTextNew__VariantsArgs;
  args: PlasmicTextNew__ArgsType;
  overrides: PlasmicTextNew__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [sty.roottitle]: hasVariant(variants, "title", "title"),
          [sty.rootwithIconLeft]: hasVariant(
            variants,
            "withIconLeft",
            "withIconLeft"
          )
        }
      )}
    >
      {(
        hasVariant(variants, "title", "title")
          ? true
          : hasVariant(variants, "withIconLeft", "withIconLeft")
          ? true
          : true
      ) ? (
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__ecrDq,
            {
              [sty.textcolors_gray__ecrDq9TY4]: hasVariant(
                variants,
                "colors",
                "gray"
              ),
              [sty.textcolors_red__ecrDqn3Gdi]: hasVariant(
                variants,
                "colors",
                "red"
              ),
              [sty.textcolors_white__ecrDqYGbX]: hasVariant(
                variants,
                "colors",
                "white"
              ),
              [sty.textsize__10__ecrDqyJsWu]: hasVariant(
                variants,
                "size",
                "_10"
              ),
              [sty.textsize__11__ecrDqVashr]: hasVariant(
                variants,
                "size",
                "_11"
              ),
              [sty.textsize__12__ecrDqFJdLx]: hasVariant(
                variants,
                "size",
                "_12"
              ),
              [sty.textsize__14__ecrDqeAQ2]: hasVariant(
                variants,
                "size",
                "_14"
              ),
              [sty.textsize__24__ecrDqDKeTy]: hasVariant(
                variants,
                "size",
                "_24"
              ),
              [sty.textsize__28__ecrDqjUSf]: hasVariant(
                variants,
                "size",
                "_28"
              ),
              [sty.texttitle__ecrDqRiF4N]: hasVariant(
                variants,
                "title",
                "title"
              ),
              [sty.textweight_medium__ecrDqpyjW]: hasVariant(
                variants,
                "weight",
                "medium"
              ),
              [sty.textweight_semiBold__ecrDqkC6Cr]: hasVariant(
                variants,
                "weight",
                "semiBold"
              ),
              [sty.textwithIconLeft__ecrDq0LNYb]: hasVariant(
                variants,
                "withIconLeft",
                "withIconLeft"
              )
            }
          )}
        >
          {"Enter some text"}
        </div>
      ) : null}
      {(
        hasVariant(variants, "title", "title")
          ? true
          : hasVariant(variants, "withIconLeft", "withIconLeft")
          ? true
          : true
      ) ? (
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox, {
            [sty.freeBoxsize__10]: hasVariant(variants, "size", "_10"),
            [sty.freeBoxsize__11]: hasVariant(variants, "size", "_11"),
            [sty.freeBoxsize__12]: hasVariant(variants, "size", "_12"),
            [sty.freeBoxsize__14]: hasVariant(variants, "size", "_14"),
            [sty.freeBoxsize__16]: hasVariant(variants, "size", "_16"),
            [sty.freeBoxsize__24]: hasVariant(variants, "size", "_24"),
            [sty.freeBoxsize__28]: hasVariant(variants, "size", "_28"),
            [sty.freeBoxtitle]: hasVariant(variants, "title", "title"),
            [sty.freeBoxweight_medium]: hasVariant(
              variants,
              "weight",
              "medium"
            ),
            [sty.freeBoxweight_semiBold]: hasVariant(
              variants,
              "weight",
              "semiBold"
            ),
            [sty.freeBoxwithIconLeft]: hasVariant(
              variants,
              "withIconLeft",
              "withIconLeft"
            )
          })}
        >
          {true ? (
            <Icon className={classNames("__wab_instance", sty.icon__pIlNq)} />
          ) : null}
        </div>
      ) : null}
      {true ? (
        <h1
          data-plasmic-name={"h1"}
          data-plasmic-override={overrides.h1}
          className={classNames(projectcss.all, projectcss.h1, sty.h1)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__g0Phb
            )}
          >
            {"Distribution"}
          </div>
        </h1>
      ) : null}
      {(hasVariant(variants, "withIconLeft", "withIconLeft") ? true : true) ? (
        <Icon
          className={classNames("__wab_instance", sty.icon__vDpIn, {
            [sty.iconwithIconLeft__vDpIn0LNYb]: hasVariant(
              variants,
              "withIconLeft",
              "withIconLeft"
            )
          })}
        />
      ) : null}
      {(hasVariant(variants, "withIconLeft", "withIconLeft") ? true : true) ? (
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__wTM3,
            {
              [sty.textwithIconLeft__wTM30LNYb]: hasVariant(
                variants,
                "withIconLeft",
                "withIconLeft"
              )
            }
          )}
        >
          {"Enter some text"}
        </div>
      ) : null}
      {(hasVariant(variants, "title", "title") ? true : true) ? (
        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text___629Xb,
            {
              [sty.texttitle___629XbRiF4N]: hasVariant(
                variants,
                "title",
                "title"
              )
            }
          )}
        >
          {"Enter some text"}
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "freeBox", "h1"],
  freeBox: ["freeBox"],
  h1: ["h1"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  h1: "h1";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicTextNew__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicTextNew__VariantsArgs;
    args?: PlasmicTextNew__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicTextNew__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicTextNew__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTextNew__ArgProps,
      internalVariantPropNames: PlasmicTextNew__VariantProps
    });

    return PlasmicTextNew__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicTextNew";
  } else {
    func.displayName = `PlasmicTextNew.${nodeName}`;
  }
  return func;
}

export const PlasmicTextNew = Object.assign(
  // Top-level PlasmicTextNew renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    h1: makeNodeComponent("h1"),

    // Metadata about props expected for PlasmicTextNew
    internalVariantProps: PlasmicTextNew__VariantProps,
    internalArgProps: PlasmicTextNew__ArgProps
  }
);

export default PlasmicTextNew;
/* prettier-ignore-end */
