// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: a7WqxJ4ZPn
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Text from "../../Text"; // plasmic-import: sIxKMhfpOf/component
import Label from "../../Label"; // plasmic-import: zvfx6kR6ll/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicNftOverview.module.css"; // plasmic-import: a7WqxJ4ZPn/css

export type PlasmicNftOverview__VariantMembers = {};

export type PlasmicNftOverview__VariantsArgs = {};
type VariantPropType = keyof PlasmicNftOverview__VariantsArgs;
export const PlasmicNftOverview__VariantProps = new Array<VariantPropType>();

export type PlasmicNftOverview__ArgsType = {};
type ArgPropType = keyof PlasmicNftOverview__ArgsType;
export const PlasmicNftOverview__ArgProps = new Array<ArgPropType>();

export type PlasmicNftOverview__OverridesType = {
  root?: p.Flex<"div">;
  label?: p.Flex<typeof Label>;
};

export interface DefaultNftOverviewProps {
  className?: string;
}

function PlasmicNftOverview__RenderFunc(props: {
  variants: PlasmicNftOverview__VariantsArgs;
  args: PlasmicNftOverview__ArgsType;
  overrides: PlasmicNftOverview__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__k5Abo)}>
        <Text className={classNames("__wab_instance", sty.text__uJntp)} />

        <Text
          className={classNames("__wab_instance", sty.text__sZgO)}
          colors={"gray" as const}
        />
      </div>

      <div className={classNames(projectcss.all, sty.freeBox___5M8Os)}>
        <Label
          data-plasmic-name={"label"}
          data-plasmic-override={overrides.label}
          className={classNames("__wab_instance", sty.label)}
          colors={"purple" as const}
        />

        <Text
          className={classNames("__wab_instance", sty.text__deNca)}
          colors={"gray" as const}
        />
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "label"],
  label: ["label"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  label: typeof Label;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNftOverview__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNftOverview__VariantsArgs;
    args?: PlasmicNftOverview__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNftOverview__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNftOverview__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNftOverview__ArgProps,
      internalVariantPropNames: PlasmicNftOverview__VariantProps
    });

    return PlasmicNftOverview__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNftOverview";
  } else {
    func.displayName = `PlasmicNftOverview.${nodeName}`;
  }
  return func;
}

export const PlasmicNftOverview = Object.assign(
  // Top-level PlasmicNftOverview renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    label: makeNodeComponent("label"),

    // Metadata about props expected for PlasmicNftOverview
    internalVariantProps: PlasmicNftOverview__VariantProps,
    internalArgProps: PlasmicNftOverview__ArgProps
  }
);

export default PlasmicNftOverview;
/* prettier-ignore-end */
