// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: mWUFULV0cz
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: IDy-UAQYMv/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicHeaderActions.module.css"; // plasmic-import: mWUFULV0cz/css

export type PlasmicHeaderActions__VariantMembers = {};

export type PlasmicHeaderActions__VariantsArgs = {};
type VariantPropType = keyof PlasmicHeaderActions__VariantsArgs;
export const PlasmicHeaderActions__VariantProps = new Array<VariantPropType>();

export type PlasmicHeaderActions__ArgsType = {};
type ArgPropType = keyof PlasmicHeaderActions__ArgsType;
export const PlasmicHeaderActions__ArgProps = new Array<ArgPropType>();

export type PlasmicHeaderActions__OverridesType = {
  root?: p.Flex<"div">;
};

export interface DefaultHeaderActionsProps {
  className?: string;
}

function PlasmicHeaderActions__RenderFunc(props: {
  variants: PlasmicHeaderActions__VariantsArgs;
  args: PlasmicHeaderActions__ArgsType;
  overrides: PlasmicHeaderActions__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <Button
        className={classNames("__wab_instance", sty.button__nvW0P)}
        colors={"defaultStroke" as const}
        size={"md" as const}
      />

      <Button
        className={classNames("__wab_instance", sty.button__e1CXg)}
        colors={"gradient" as const}
        size={"md" as const}
      />
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicHeaderActions__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicHeaderActions__VariantsArgs;
    args?: PlasmicHeaderActions__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicHeaderActions__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicHeaderActions__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHeaderActions__ArgProps,
      internalVariantPropNames: PlasmicHeaderActions__VariantProps
    });

    return PlasmicHeaderActions__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHeaderActions";
  } else {
    func.displayName = `PlasmicHeaderActions.${nodeName}`;
  }
  return func;
}

export const PlasmicHeaderActions = Object.assign(
  // Top-level PlasmicHeaderActions renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements

    // Metadata about props expected for PlasmicHeaderActions
    internalVariantProps: PlasmicHeaderActions__VariantProps,
    internalArgProps: PlasmicHeaderActions__ArgProps
  }
);

export default PlasmicHeaderActions;
/* prettier-ignore-end */
