// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: ujWBNnbL2n4RZDdiZiYFdw
// Component: YHwpijO3GT
import * as React from "react";

import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";

import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import Text from "../../Text"; // plasmic-import: sIxKMhfpOf/component
import Progress from "../../Progress"; // plasmic-import: OiFeVBevre/component

import "@plasmicapp/react-web/lib/plasmic.css";

import projectcss from "./plasmic_marsbase_components.module.css"; // plasmic-import: ujWBNnbL2n4RZDdiZiYFdw/projectcss
import sty from "./PlasmicNftProgress.module.css"; // plasmic-import: YHwpijO3GT/css

export type PlasmicNftProgress__VariantMembers = {};

export type PlasmicNftProgress__VariantsArgs = {};
type VariantPropType = keyof PlasmicNftProgress__VariantsArgs;
export const PlasmicNftProgress__VariantProps = new Array<VariantPropType>();

export type PlasmicNftProgress__ArgsType = {};
type ArgPropType = keyof PlasmicNftProgress__ArgsType;
export const PlasmicNftProgress__ArgProps = new Array<ArgPropType>();

export type PlasmicNftProgress__OverridesType = {
  root?: p.Flex<"div">;
  progress?: p.Flex<typeof Progress>;
};

export interface DefaultNftProgressProps {
  className?: string;
}

function PlasmicNftProgress__RenderFunc(props: {
  variants: PlasmicNftProgress__VariantsArgs;
  args: PlasmicNftProgress__ArgsType;
  overrides: PlasmicNftProgress__OverridesType;

  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;
  const $props = props.args;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root
      )}
    >
      <div className={classNames(projectcss.all, sty.freeBox__rXaKk)}>
        <Text className={classNames("__wab_instance", sty.text___9PisI)} />

        <Text
          className={classNames("__wab_instance", sty.text__zihki)}
          colors={"gray" as const}
        />
      </div>

      <Progress
        data-plasmic-name={"progress"}
        data-plasmic-override={overrides.progress}
        className={classNames("__wab_instance", sty.progress)}
      />

      <div className={classNames(projectcss.all, sty.freeBox__alQaI)}>
        <div className={classNames(projectcss.all, sty.freeBox__liJ0Q)}>
          <Text className={classNames("__wab_instance", sty.text__x7M6W)} />

          <Text
            className={classNames("__wab_instance", sty.text__h2WVd)}
            colors={"gray" as const}
          />
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__urVXg)}>
          <Text className={classNames("__wab_instance", sty.text__izpqy)} />

          <Text
            className={classNames("__wab_instance", sty.text__cC5Hw)}
            colors={"gray" as const}
          />
        </div>
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "progress"],
  progress: ["progress"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  progress: typeof Progress;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicNftProgress__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicNftProgress__VariantsArgs;
    args?: PlasmicNftProgress__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicNftProgress__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicNftProgress__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicNftProgress__ArgProps,
      internalVariantPropNames: PlasmicNftProgress__VariantProps
    });

    return PlasmicNftProgress__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicNftProgress";
  } else {
    func.displayName = `PlasmicNftProgress.${nodeName}`;
  }
  return func;
}

export const PlasmicNftProgress = Object.assign(
  // Top-level PlasmicNftProgress renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    progress: makeNodeComponent("progress"),

    // Metadata about props expected for PlasmicNftProgress
    internalVariantProps: PlasmicNftProgress__VariantProps,
    internalArgProps: PlasmicNftProgress__ArgProps
  }
);

export default PlasmicNftProgress;
/* prettier-ignore-end */
