name: Build image on tag
on: 
  push:
    tags:
      - 'v*'

env:
  deployment_name: token-dashboard-dev

jobs:
  push_to_registry:
    name: Push to GitHub registry by Tags
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        run: echo "VERSION=$(echo $GITHUB_REF | cut -d / -f 3)" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: build&push
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}
          tags: ${{ env.VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Checkout k8s
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.MB_GITHUB_TOKEN }}
          repository: otcmarsbase/k8s
          
      - name: Update files
        run: ./scripts/latest.sh ${{ env.deployment_name }} ${{ env.VERSION }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: ${{ env.deployment_name }}
          token: ${{ secrets.MB_GITHUB_TOKEN }}
          commit-message: Upgraded  ${{ github.repository }} to ${{ env.VERSION }}
          title: 🆕 Upgraded ${{ github.repository }} to ${{ env.VERSION }}
